Update storage.md
elixir-europe/rdm-toolkit pull request #262
Opened 2020-12-11 09:36 UTC by YvonneKallberg

Issue #259  

This PR includes a new section 'How store your data after a project ends?' as well as suggestions that address the comments I've made in the issue about clarifying the question 'How to store your data during the course of your project?' I have also updated links to Data Sensitivity page.

2020-12-14 14:05 UTC, YvonneKallberg commented
I now realize that I've updated security & privacy links to a page, Data sensitivity, that is not complete and thus not available on the web. Should the links to go Your domain - human data instead / in the meantime? The only thing missing is that it is not only human data that can be considered sensitive (but in reality I think most of the time it is human data that is the worry / main research focus).

2020-12-16 20:52 UTC, pinarpink commented
Hi @YvonneKallberg  we will keep the `data_sensitivity` page in fact we decided to rename it to `data_classification`  according to the new structure and naming. In the data_classification page we will be able to talk about other kinds of sensitive data on that page. 

@bedroesb what is your suggestion, I think we can merge this PR before the overhaul and fix any broken links later on.

2020-12-16 20:53 UTC, pinarpink approved these changes

2020-12-17 10:05 UTC, bedroesb commented
@YvonneKallberg and @pinarpink , yes, GDPR became Data protection and Data sensitivity became Data classification. I fixed this PR accordingly, can you check if I did it correct?

2020-12-18 08:09 UTC, YvonneKallberg commented on pages/your_problem/storage.md
> +For sensitive data, consider the [Data Sensitivity guidelines](data_classification).
Change to [Data **Classification** guidelines] instead of [Data **Sensitivity** guidelines]

2021-01-07 17:31 UTC, floradanna requested changes
Thanks for this contribution!
Could you please add e!DAL and RDMP into the [tools and resources table](https://rdm.elixir-europe.org/tool_resource_update.html#making-changes)?

2021-01-07 17:43 UTC, bedroesb commented
The respective tag you want to use for the tools in this case is `storage`

2021-01-08 09:03 UTC, YvonneKallberg commented
I've added e!DAL and RDMP to the tools list.

2021-01-08 10:19 UTC, floradanna approved these changes

2021-01-08 10:20 UTC, merged