contribution overview process added
elixir-europe/rdm-toolkit pull request #72
Opened 2020-09-16 15:01 UTC by pinarpink

Adresses https://github.com/elixir-europe/rdm-toolkit/issues/19

Some work still needs to be done though.

2020-09-16 15:03 UTC, bedroesb commented
is it possible to export the diagram to svg instead of png? :)

2020-09-16 15:04 UTC, pinarpink commented
@bedroesb  ok let me do svg

2020-09-17 08:59 UTC, pinarpink commented
@bedroesb   this should be good to go. let me know.

2020-09-17 09:04 UTC, nsoranzo commented on pages/contribute/how_to_contribute.md
> +* **Github way:** We use git to develop the RDM toolkit website. Git allows us to accept and coordinate contributions under an open authoring and review process. Therefore, GitHub is our preferred wa
```suggestion
* **Github way:** We use GitHub to develop the RDM toolkit website. GitHub allows us to accept and coordinate contributions under an open authoring and review process. Therefore, this is our preferred way of accepting contributions. To begin with, you'll need a personal GitHub account, which you can create [here](https://github.com/join).   
```

2020-09-17 09:04 UTC, nsoranzo commented on pages/contribute/how_to_contribute.md
> +* **Google Doc way:** For those contributors that are not versed in git, we provide Google Doc templates. This approach requires e-mail communication with our editors, who will be responsible for tra
```suggestion
* **Google Doc way:** Alternatively, we provide Google Doc templates. This approach requires e-mail communication with our editors, who will be responsible for transferring the content to our git repository on your behalf.
```

2020-09-17 09:07 UTC, bedroesb commented
Looks good! Only comment I have is that in order to let the image show up correctly you have to change `![image](images/howto_contribute_overview.svg) <br/>` to `{% include image.html file="howto_contribute_overview.svg" caption="Figure 1. How to contribute overview." alt="How to contribute overview" %}`

+ I don't think the </br> are needed in this case when you leave a whitespace in between :) 

For more information about the syntax you can always visit the [demo page](https://elixir-europe.github.io/rdm-toolkit/demo_page.html)

2020-09-17 09:17 UTC, bedroesb requested changes

2020-09-17 09:17 UTC, bedroesb commented on pages/contribute/how_to_contribute.md
> +![image](images/howto_contribute_overview.svg) <br/>
```suggestion
{% include image.html file="howto_contribute_overview.svg" alt="How to contribute overview" %}
```

2020-09-17 09:17 UTC, bedroesb commented on pages/contribute/how_to_contribute.md
> +* **Github way:** We use git to develop the RDM toolkit website. Git allows us to accept and coordinate contributions under an open authoring and review process. Therefore, GitHub is our preferred wa
```suggestion
* **[Github way:](github_way)** We use git to develop the RDM toolkit website. Git allows us to accept and coordinate contributions under an open authoring and review process. Therefore, GitHub is our preferred way of accepting contributions. To begin with, you'll need a personal GitHub account, which you can create [here](https://github.com/join).   
```

2020-09-17 09:17 UTC, bedroesb commented on pages/contribute/how_to_contribute.md
> +* **Google Doc way:** For those contributors that are not versed in git, we provide Google Doc templates. This approach requires e-mail communication with our editors, who will be responsible for tra
```suggestion
* **[Google Doc way:](google_doc_way)** For those contributors that are not versed in git, we provide Google Doc templates. This approach requires e-mail communication with our editors, who will be responsible for transferring the content to our git repository on your behalf.
```
I added the links to the separate pages

2020-09-17 09:17 UTC, bedroesb commented on pages/contribute/how_to_contribute.md
> +<br/>
```suggestion
```

2020-09-17 09:17 UTC, bedroesb commented on pages/contribute/how_to_contribute.md
> +We accept contributions in two ways sketched below, through GitHub or through Google Docs. <br/>
```suggestion
We accept contributions in two ways sketched below, through GitHub or through Google Docs.
```

2020-09-17 09:47 UTC, bedroesb approved these changes

2020-09-17 09:57 UTC, merged